Controllers/CustomerDetailsController.cs
using Gym.Data;
using Gym.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Gym.Controllers
{
    
        [Authorize(Roles = SD.Role_Admin)]
        public class CustomerDetailsController : Controller
        {
            private readonly ApplicationDbContext _db;
            public CustomerDetailsController(ApplicationDbContext db)
            {
                _db = db;
            }

            public IActionResult Index()
            {
                List<ApplicationUser> objApplicationUserList = _db.ApplicationUser.ToList();
                return View(objApplicationUserList);
            }

            
            

            //public IActionResult Delete(string? Id)
            //{
            //    if (Id == null )
            //    {
            //        return NotFound();
            //    }

            //    ApplicationUser customerFromDB = _db.ApplicationUser.Find(Id);
               
            //    if (customerFromDB == null)
            //    {
            //        return NotFound();
            //    }
            //    return View(customerFromDB);
            //}

           
            public IActionResult DeletePOST(string? Id)
            {
                ApplicationUser obj = _db.ApplicationUser.Find(Id);
                if (obj == null)
                {
                    return NotFound();
                }
                else
                {
                    _db.ApplicationUser.Remove(obj);
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
        }
}

Views/CustomerDetails/Index.cshtml
@model List<ApplicationUser>;
@{
    ViewData["Title"] = "Admin Page";
    Layout = "~/Views/Shared/_akadminpg.cshtml";
}

<style>
    .table thead {
        background-color: #343a40; /* Dark background color */
        color: #fff; /* White text color */
    }

    .table tbody tr,
    .table tbody th,
    .table tbody td {
        color: #000; /* Dark text color */
    }

    .white-text {
        color: #fff; /* White text color */
    }
</style>

<div class="container mt-5 pt-5">
    <div class="row pt-4 pb-3">
        <div class="col-6">
            <h2 class="text-dark">Customer Details</h2>
        </div>
    </div>
    <div class="table-responsive">
        <table class="table table-bordered">    
        <thead>
            <tr>
                <th class="white-text">
                    Customer Name
                </th>
                <th class="white-text">
                    Gender
                </th>
                <th class="white-text">
                    Phone Number
                </th>
                <th class="white-text">
                    Remove customer
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td>@obj.FullName</td>
                    <td>@obj.Gender</td>
                    <td>@obj.PhoneNumber</td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            
                            <a asp-controller="CustomerDetails" asp-action="DeletePOST" asp-route-id="@obj.Id" class="btn btn-danger mx-2">
                                <i class="bi bi-trash-fill"></i>  Remove
                            </a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
</div>





            