Models/Exercise.cs
using System.ComponentModel.DataAnnotations;

namespace Gym.Models
{
    public class Exercise
    {
        [Key]
        [Required]
        public int Id { get; set; }
        [Required]
        [MaxLength (30)]
        public string MuscleGroup { get; set; }
        [Required]
        [MaxLength(30)]
        public string ExerciseName { get; set; } 
    }
}

Controllers/ExerciseController.cs
using Gym.Data;
using Gym.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Gym.Controllers
{
    [Authorize(Roles = SD.Role_Admin)]
    public class ExerciseController : Controller
    {
        private readonly ApplicationDbContext _db;
        public ExerciseController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            List<Exercise> objExerciseList = _db.ExerciseDetail.ToList();
            return View(objExerciseList);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Exercise obj)
        {
            if (ModelState.IsValid)
            {
                _db.ExerciseDetail.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            Exercise ExerciseFromDB = _db.ExerciseDetail.Find(id);
            Exercise ExerciseFromDB1 = _db.ExerciseDetail.FirstOrDefault(u => u.Id == id);
            Exercise ExerciseFromDB2 = _db.ExerciseDetail.Where(u => u.Id == id).FirstOrDefault();

            if (ExerciseFromDB == null)
            {
                return NotFound();
            }
            return View(ExerciseFromDB);
        }
        [HttpPost]
        public IActionResult Edit(Exercise obj)
        {
            if (ModelState.IsValid)
            {
                _db.ExerciseDetail.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            Exercise ExerciseFromDB = _db.ExerciseDetail.Find(id);
            Exercise ExerciseFromDB1 = _db.ExerciseDetail.FirstOrDefault(u => u.Id == id);
            Exercise ExerciseFromDB2 = _db.ExerciseDetail.Where(u => u.Id == id).FirstOrDefault();

            if (ExerciseFromDB == null)
            {
                return NotFound();
            }
            return View(ExerciseFromDB);
        }


        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePOST(int? id)
        {
            Exercise obj = _db.ExerciseDetail.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            else
            {
                _db.ExerciseDetail.Remove(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
        }
    }
}

Views/Exercise/Create.cshtml
@model Exercise
@{
    ViewData["Title"] = "Admin Page";
    Layout = "~/Views/Shared/_akadminpg.cshtml";
}

<h1>hello</h1>
<form method="post">
    <div class="border p-3 pt-5 mt-5">
        <div class="text-primary">
            <h2>Register a new Exercise</h2>
            <hr />
        </div>

        <div class="mb-3 row">
            <label asp-for="MuscleGroup" class="p-0"></label>
            <input asp-for="MuscleGroup" type="text" class="form-control" />
            <span asp-validation-for="MuscleGroup" class="text-danger"></span>
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="ExerciseName" class="p-0"></label>
            <input asp-for="ExerciseName" type="text" class="form-control" />
            <span asp-validation-for="ExerciseName" class="text-danger"></span>
        </div>

        <div class="mb-3 row p-1">
            <div class="col-6 col-md-4">
                <button type="submit" class="btn btn-primary form-control">Resgister</button>
            </div>

            <div class="col-6 col-md-4">
                <a asp-controller="Exercise" asp-action="Index" class="btn btn-outline-secondary form-control">
                    Back to Exerises
                </a>
            </div>
        </div>
</form>

Views/Exercise/Delete.cshtml
@model Exercise
@{
    ViewData["Title"] = "Admin Page";
    Layout = "~/Views/Shared/_akadminpg.cshtml";
}

<form method="post">
    <input asp-for="Id" hidden />
    <div class="border p-3 pt-5 mt-5">
        <div class="text-primary">
            <h2>Remove Customer </h2>
            <hr />
        </div>

        <div class="mb-3 row">
            <label asp-for="MuscleGroup" class="p-0"></label>
            <input asp-for="MuscleGroup" disabled type="text" class="form-control" />
       
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="ExerciseName" class="p-0"></label>
            <input asp-for="ExerciseName" disabled type="text" class="form-control" />

        <div class="mb-3 row p-1">
            <div class="col-6 col-md-4">
                <button type="submit" class="btn btn-danger form-control">Remove</button>
            </div>

            <div class="col-6 col-md-4">
                <a asp-controller="Exercise" asp-action="Index" class="btn btn-outline-secondary form-control">
                    Back to Exercises
                </a>
            </div>
        </div>
</form>

Views/Exercise/Edit.cshtml
@model Exercise
@{
    ViewData["Title"] = "Admin Page";
    Layout = "~/Views/Shared/_akadminpg.cshtml";
}

<form method="post">
    <div class="border p-3 pt-5 mt-5">
        <div class="text-primary">
            <h2>Edit Customer Details</h2>
            <hr />
        </div>

        <div class="mb-3 row">
            <label asp-for="MuscleGroup" class="p-0"></label>
            <input asp-for="MuscleGroup" type="text" class="form-control" />
            <span asp-validation-for="MuscleGroup" class="text-danger"></span>
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="ExerciseName" class="p-0"></label>
            <input asp-for="ExerciseName" type="text" class="form-control" />
            <span asp-validation-for="ExerciseName" class="text-danger"></span>
        </div>


        <div class="mb-3 row p-1">
            <div class="col-6 col-md-4">
                <button type="submit" class="btn btn-primary form-control">Update Detials</button>
            </div>

            <div class="col-6 col-md-4">
                <a asp-controller="Exercise" asp-action="Index" class="btn btn-outline-secondary form-control">
                    Back to Customer List
                </a>
            </div>
        </div>
</form>

Views/Exercise/Index.cshtml
@model List<Exercise>;
@{
    ViewData["Title"] = "Admin Page";
    Layout = "~/Views/Shared/_akadminpg.cshtml";
}

<div class="container pt-5 mt-5">
    <div class="row pt-4 pb-3">
        <div class="col-6">
            <h2 class="text-primary">Exercise Details</h2>
        </div>
       @*  <div class="col-6 text-end">
            <a asp-controller="Exercise" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-square"></i> Register New Exercise
            </a>
        </div> *@
    </div>
    <table class=" table table-bordered ">
        <thead>
            <tr>
                <th>
                    Muscle Group
                </th>
                <th>
                    Exercise
                </th>
                <th>
                    Edit Details
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td>@obj.MuscleGroup</td>
                    <td>@obj.ExerciseName</td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Exercise" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary mx-2">
                                <i class="bi bi-pencil-square"></i>  Edit
                            </a>
                            <a asp-controller="Exercise" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger mx-2">
                                <i class="bi bi-trash-fill"></i>  Remove
                            </a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>